#!/usr/bin/env python3
"""Generate docs/WORKED_EXAMPLES.md by recomputing selected player-seasons step by step.

Recomputes from the raw input totals (not from the engine), using the release
outputs only for league-season reference populations (means/SDs, team defense Z,
role/defense tiers) and verified appearance MOV. Fails if any recomputed score
differs from the release output by more than 1e-9.
"""
from __future__ import annotations

import argparse
import math
from pathlib import Path

import numpy as np
import pandas as pd

ROLE = {1: 1.00, 2: 0.85, 3: 0.35, 4: 0.15}
DEF = {1: 1.00, 2: 0.60, 3: 0.25, 4: 0.00}
EXAMPLES = [
    ("Ordinary season", "jamesle01", 2009, "NBA"),
    ("Traded season", "mccolcj01", 2022, "NBA"),
    ("Shortened season (50-game 1999 schedule)", "duncati01", 1999, "NBA"),
    ("ABA season", "ervinju01", 1976, "ABA"),
    ("Pre-1958 season", "mikange01", 1952, "NBA"),
    ("Latest completed season", "jokicni01", 2025, "NBA"),
]
# Team-defense example: every step of the season-totals possession estimate for one team.
TEAM_EXAMPLE = (1964, "NBA", "BOS")
COEF = (0.6020313823981741, 0.8571267229514948, 0.32977975821588174)


def f(x, d=4):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return "—"
    return f"{(round(x, d) + 0.0):,.{d}f}"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--input-dir", type=Path, required=True)
    ap.add_argument("--release-dir", type=Path, required=True)
    ap.add_argument("--out", type=Path, required=True)
    a = ap.parse_args()
    rt = dict(float_precision="round_trip", low_memory=False)
    P = pd.read_csv(a.input_dir / "Player Totals.csv")
    T = pd.read_csv(a.input_dir / "Team Totals.csv")
    O = pd.read_csv(a.input_dir / "Opponent Totals.csv")
    T = T[T.team.ne("League Average")]
    O = O[O.team.ne("League Average")]
    ps = pd.read_csv(a.release_dir / "cv_player_seasons.csv", **rt)
    st = pd.read_csv(a.release_dir / "cv_player_stints.csv", **rt)
    td = pd.read_csv(a.release_dir / "team_defense.csv", **rt)

    lines = ["# Court Value 1.1: worked examples", "",
             "Generated by `worked_examples.py` from the declared input snapshot and the release-candidate outputs. "
             "Each production step below is recomputed from raw season totals, independently of the engine; league-season "
             "reference statistics (means and population SDs), tier assignments and appearance-game MOV are read from the release files; "
             "team defensive Z is read from the release for player examples and recomputed from raw totals for the team example. The script fails if any recomputed score differs from the published value by more than 1e-9. "
             "Values are shown to four decimals; calculations use full precision.", ""]
    worst = 0.0
    # --- team defense, recomputed from raw season totals ---
    season, lg, team = TEAM_EXAMPLE
    L = T[(T.season == season) & (T.lg == lg)].merge(O[["season", "lg", "abbreviation", "opp_pts"]], on=["season", "lg", "abbreviation"])
    L = L.dropna(subset=["g", "pts", "fga", "fta", "trb", "opp_pts"]).copy()
    L["att"] = L.fga + 0.44 * L.fta
    feats = {"x1": np.log(L.opp_pts / L.pts), "x2": np.log(L.pts / L.att), "x3": np.log(L.trb / L.att)}
    for k, v in feats.items():
        L[k] = v - v.mean()
    L["est"] = L.att * np.exp(COEF[0] * L.x1 + COEF[1] * L.x2 + COEF[2] * L.x3)
    lpsa_t = L.pts.sum() / L.att.sum()
    L["psa_sup"] = lpsa_t - L.opp_pts / L.est
    L["ppg"] = L.opp_pts / L.g
    L["ppg_sup"] = L.ppg.mean() - L.ppg
    zp = lambda v: (v - v.mean()) / v.std(ddof=0)
    L["tdz"] = 0.8 * zp(L.psa_sup) + 0.2 * zp(L.ppg_sup)
    r = L[L.abbreviation == team].iloc[0]
    pub = td[(td.season == season) & (td.lg == lg)].set_index("team").team_def_z_universal
    worst = max(worst, float((L.set_index("abbreviation").tdz - pub).abs().max()))
    lines += [f"## Team defense: {season} {lg} {r.team}", "",
              "Opponent attempts were not recorded before 1970-71, so CV 1.1 estimates them for every season from team totals recorded since 1951-52. "
              f"League-season means are over the {len(L)} teams.", "",
              "| Step | Value |", "|---|---:|",
              f"| Own attempts = FGA + .44·FTA = {int(r.fga)} + .44·{int(r.fta)} | {f(r.att, 2)} |",
              f"| d ln(OppPTS/PTS) = ln({int(r.opp_pts)}/{int(r.pts)}) − league mean | {f(r.x1)} |",
              f"| d ln(PTS/OwnAtt) | {f(r.x2)} |",
              f"| d ln(TRB/OwnAtt), TRB = {int(r.trb)} | {f(r.x3)} |",
              f"| Estimated opponent attempts = OwnAtt·exp({COEF[0]:.4f}·x1 + {COEF[1]:.4f}·x2 + {COEF[2]:.4f}·x3) | {f(r.est, 2)} |",
              f"| LeaguePSA = league PTS / league attempts | {f(lpsa_t)} |",
              f"| PSA suppression = LeaguePSA − OppPTS/EstOppAtt | {f(r.psa_sup)} |",
              f"| PPG suppression = league mean opp PPG − {f(r.ppg, 2)} | {f(r.ppg_sup)} |",
              f"| **TeamDef = .80·Z(PSA suppression) + .20·Z(PPG suppression)** | **{f(r.tdz)}** (published {f(float(pub[team]))}) |", ""]
    for title, pid, season, lg in EXAMPLES:
        row = ps[(ps.player_id == pid) & (ps.season == season) & (ps.lg == lg)].iloc[0]
        stints = st[(st.player_id == pid) & (st.season == season) & (st.lg == lg)]
        pool = ps[(ps.season == season) & (ps.lg == lg) & ps.rate.notna()]
        tl = T[(T.season == season) & (T.lg == lg)]
        lpsa = tl.pts.sum() / (tl.fga.sum() + 0.44 * tl.fta.sum())
        tm = tl.merge(O[["season", "lg", "abbreviation", "opp_pts"]], on=["season", "lg", "abbreviation"])
        tm["mov"] = (tm.pts - tm.opp_pts) / tm.g
        mov_mean, mov_sd = tm.mov.mean(), tm.mov.std(ddof=0)
        lines += [f"## {title}: {row.player}, {season} {lg}", "",
                  f"League-season constants: LeaguePSA = {f(lpsa)}; team full-season MOV mean = {f(mov_mean)}, population SD = {f(mov_sd)}.", ""]
        lines += ["| Step | " + " | ".join(stints.team) + " |", "|---|" + "---:|" * len(stints)]
        rows = {k: [] for k in ["G / team G", "PTS, AST, TRB", "FGA, FTA", "Attempts = FGA + .44·FTA", "BoxImpact = PTS + .65·AST + .65·TRB",
                                "EffAdj = .30·(PTS − .92·LeaguePSA·Attempts)", "PaceAdj = 2·TeamPTS/(TeamPTS+OppPTS)",
                                "Role tier → weight", "MOV method", "MOV used", "ContextZ = (MOV − mean)/SD",
                                "Context = 1 + .125·w·tanh(.75·Z)", "Raw = (Box + Eff)·PaceAdj·Context",
                                "Minutes; defensive tier → weight", "Team defensive Z", "DefRaw_stint = TeamDefZ × weight"]}
        raw_total = 0.0
        def_num = def_mp = 0.0
        for _, s in stints.iterrows():
            src = P[(P.player_id == pid) & (P.season == season) & (P.lg == lg) & (P.team == s.team)].iloc[0]
            t = tm[tm.abbreviation == s.team].iloc[0]
            att = src.fga + 0.44 * src.fta
            box = src.pts + 0.65 * src.ast + 0.65 * src.trb
            eff = 0.30 * (src.pts - 0.92 * lpsa * att)
            pace = 2 * t.pts / (t.pts + t.opp_pts)
            w = ROLE[int(s.role_tier)]
            z = (s.mov_used - mov_mean) / mov_sd
            ctx = 1 + 0.125 * w * math.tanh(0.75 * z)
            raw = (box + eff) * pace * ctx
            raw_total += raw
            worst = max(worst, abs(raw - s.raw_stint))
            dw = DEF[int(s.def_tier)]
            tz = td[(td.season == season) & (td.lg == lg) & (td.team == s.team)].team_def_z_universal
            tz = float(tz.iloc[0]) if len(tz) else float("nan")
            dr = tz * dw
            if not math.isnan(dr):
                def_num += dr * src.mp
                def_mp += src.mp
            rows["G / team G"].append(f"{int(src.g)} / {int(t.g)}")
            rows["PTS, AST, TRB"].append(f"{int(src.pts)}, {int(src.ast)}, {int(src.trb)}")
            rows["FGA, FTA"].append(f"{int(src.fga)}, {int(src.fta)}")
            rows["Attempts = FGA + .44·FTA"].append(f(att, 2))
            rows["BoxImpact = PTS + .65·AST + .65·TRB"].append(f(box, 2))
            rows["EffAdj = .30·(PTS − .92·LeaguePSA·Attempts)"].append(f(eff))
            rows["PaceAdj = 2·TeamPTS/(TeamPTS+OppPTS)"].append(f(pace))
            rows["Role tier → weight"].append(f"{int(s.role_tier)} → {w:.2f}")
            method = s.mov_method.replace("VERIFIED_LITERAL_APPEARANCE", "verified appearance").replace("FULL_SEASON_FALLBACK", "full-season fallback")
            if isinstance(s.fallback_reason, str) and s.fallback_reason:
                method += f" ({s.fallback_reason})"
            rows["MOV method"].append(method)
            mov_txt = f(s.mov_used)
            if s.mov_method == "VERIFIED_LITERAL_APPEARANCE":
                mov_txt += f" (full season {f(s.mov_full_season)})"
            rows["MOV used"].append(mov_txt)
            rows["ContextZ = (MOV − mean)/SD"].append(f(z))
            rows["Context = 1 + .125·w·tanh(.75·Z)"].append(f(ctx))
            rows["Raw = (Box + Eff)·PaceAdj·Context"].append(f(raw, 3))
            rows["Minutes; defensive tier → weight"].append(f"{int(src.mp)}; {int(s.def_tier)} → {dw:.2f}")
            rows["Team defensive Z"].append(f(tz))
            rows["DefRaw_stint = TeamDefZ × weight"].append(f(dr))
        for k, v in rows.items():
            lines.append(f"| {k} | " + " | ".join(v) + " |")
        G = int(stints.g.sum())
        rate = raw_total / G
        mu = np.average(pool.rate, weights=pool.G)
        sd = float(np.sqrt(np.average((pool.rate - mu) ** 2, weights=pool.G)))
        base = 3 * (rate - mu) / sd
        worst = max(worst, abs(base - row.cv_base))
        lines += ["", "Player-season aggregation:", "",
                  f"- RawTotal = Σ Raw = {f(raw_total, 3)}; Games = {G}; **Rate = RawTotal / Games = {f(rate)}**.",
                  f"- League-season rate population: {len(pool)} scorable {lg} player-seasons (qualified or not), weighted by games played ({int(pool.G.sum())} player-games): weighted mean {f(mu)}, weighted population SD {f(sd)}.",
                  f"- **CV_BASE = 3 × (Rate − weighted mean)/weighted SD = {f(base)}** (published {f(row.cv_base)}).",
                  f"- Availability = min(1, {G} / {int(row.max_team_games)}) (reference schedule) = {f(row.availability, 3)} → {'qualified' if row.qualified else 'not qualified'} (threshold 0.70; integer rule 10·G ≥ 7·team games)."]
        if def_mp > 0 and not math.isnan(row.def_raw) and not pd.isna(row.cv_full):
            draw = def_num / def_mp
            dpool = ps[(ps.season == season) & (ps.lg == lg) & ps.def_raw.notna()]
            dmu, dsd = dpool.def_raw.mean(), dpool.def_raw.std(ddof=0)
            idx = 3 * (draw - dmu) / dsd
            signed = 1.5 * math.tanh(idx / 6)
            credit = signed if signed >= 0 else 0.5 * signed
            full = base + credit
            worst = max(worst, abs(credit - row.def_credit), abs(full - row.cv_full))
            lines += [f"- DefRaw = Σ(MP × DefRaw_stint)/Σ MP = {f(draw)}; league-season defensive population {len(dpool)} rows, mean {f(dmu)}, SD {f(dsd)}.",
                      f"- DefIndex = 3 × Z = {f(idx)}; signed credit 1.5·tanh(DefIndex/6) = {f(signed)}; {'positive, kept in full' if signed >= 0 else 'negative, halved'} → **DefCredit = {f(credit)}**.",
                      f"- **CV (full) = CV_BASE + DefCredit = {f(full)}** (published {f(row.cv_full)}); season rank {int(row.full_rank_season)}, all-time qualified rank {int(row.full_rank_alltime)}.",
                      f"- Defense coverage: `{row.defense_coverage}`. Full-season-MOV control CV: {f(row.control_cv_full)}."]
        else:
            lines += [f"- Full CV: **unavailable** (`{row.defense_coverage}`). Published as `{row.score_basis}` / `{row.score_status}`; "
                      f"CV_BASE season rank {int(row.base_rank_season) if not pd.isna(row.base_rank_season) else '—'}. It must not appear on the full-CV leaderboard and must be labeled CV_BASE wherever shown."]
        lines += [f"- MOV basis for the player-season: `{row.mov_basis}`.", ""]
    lines += [f"Maximum absolute difference between these recomputations and published values: {worst:.3g}.", ""]
    if worst > 1e-9:
        raise SystemExit(f"Worked example mismatch {worst}")
    a.out.write_text("\n".join(lines))
    print("max error", worst)


if __name__ == "__main__":
    main()
